name: Docker-Build

on:
  workflow_run:
    workflows: ["Code-Coverage"]  # Name of the first workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Set up Docker
          uses: docker/setup-buildx-action@v1

        - name: Build and push Docker image
          run: |
            docker build -t iac1 .
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker tag iac1 ${{ secrets.DOCKER_USERNAME }}/iac1
            docker push ${{ secrets.DOCKER_USERNAME }}/iac1
